# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('receptions', models.IntegerField()),
                ('receiving_yards', models.IntegerField()),
                ('touchdowns', models.IntegerField()),
                ('position', models.CharField(max_length=4)),
            ],
        ),
    ]
